### ISSUE TITLE
How can I find these head files in MayaLiveLinkPlugin.cpp

### ISSUE THREAD

**Issue by lzy-InTheRain** [ue4plugins/MayaLiveLink#17]
![image](https://user-images.githubusercontent.com/72912291/126579654-69d4c40e-7059-4dc5-956d-ab5ec291b351.png)

**Comment by mattyjams** [comment]
All of the header files identified here are from various modules of the engine itself rather than the Maya Live Link plugin. For example, the "Roles" headers are from the `LiveLinkInterface` module, which for UE 5.0 can be found here:

```Engine/Source/Runtime/LiveLinkInterface/Public/Roles```

In general, you're likely to find these headers under the `Public` directory of some module in the engine.

At this point, the Maya Live Link plugin has been deprecated in favor of the Unreal Live Link for Autodesk Maya plugin which has additional features and will receive ongoing support going forward. You can find more information about the new plugin at the Autodesk repository here:

https://github.com/Autodesk/LiveLink

Closing this out...
